@url = http://localhost:7000


### Get all Comments
GET {{url}}/comments


### Create a new Comment for beauty

POST {{url}}/comments
Content-Type: application/json

{
    "type":"beauty",
    "beauty":"62a83ff477130b629b982cc3",
    "message":"What a great Idea!"
}




### Create a new Comment for recipe

POST {{url}}/comments
Content-Type: application/json

{
    "type":"recipe",
    "recipe":"62a83ac21fa5dfc2756100f1",
    "message":"Did I get depression wehn I eat the cake?"
}


### Create a new Comment for artsCraft

POST {{url}}/comments
Content-Type: application/json

{
    "type":"artsCraft",
    "artsCraft":"62a855d4e0d94da7d4fbdd34",
    "message":"this is awesome!!!"
}



### Create a new Comment for garden

POST {{url}}/comments
Content-Type: application/json

{
    "type":"garden",
    "garden":"62a305f05acc5b98cc41d7c7",
    "message":"this is awesome!!!"
}


### Create a new Comment for event

POST {{url}}/comments
Content-Type: application/json

{
    "type":"event",
    "event":"62a7421319bcc097c8eb4f21",
    "message":"I was there last week, very good selection"
}


### Edit a comment

PATCH {{url}}/comments/62a72e369bc10ecf19fba052
Content-Type: application/json

{
    "message":"edit a comment"
}


### Delete a comment

DELETE {{url}}/comments/62a72e369bc10ecf19fba052


### Like a comment
PATCH  {{url}}/comments/62a72e369bc10ecf19fba052/like
Content-Type: application/json