@url = http://localhost:7000

### GET ALL USERS ###
GET {{url}}/user

### GET SEARCH RESULT ###
GET {{url}}/user/search/N

### GET USER BY ID ###
GET {{url}}/user/62a6f394c8e66d8b453536b9


### POST/REGISTER NEW USER ###
POST {{url}}/user/register
Content-Type: application/json

{
  "firstName": "jadel",
  "lastName": "smith",
  "profileName": "jade_smith",
  "profilePicture": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50",
  "email": "js@gravatar.com",
  "password": "supPergutesgeheimespassword-123",
  "confirmPassword": "supPergutesgeheimespassword-123",
  "userAddress": {
    "street": "123 Main St",
    "city": "city",
    "zip": "12345",
    "country": "france"
  }
}

### POST/REGISTER NEW USER ###
POST {{url}}/user/register
Content-Type: application/json

{
     "firstName": "Murad",
  "lastName": "Muqbel",
  "profileName": "Murad",
  "profilePicture": "",
  "email": "Muqbel@gmail.com",
  "password": "supPergutesgeheimespassword-123",
  "confirmPassword": "supPergutesgeheimespassword-123",
  "userAddress": {
    "street": "wintergarten-allee.",
    "city": "Berlin",
    "zip": "17167",
    "country": "germany"
  }
}


### POST / USER LOGIN ###
POST {{url}}/user/login
Content-Type: application/json

{
  "email": "js@gravatar.com",
  "password": "Mypassword123!"
}

### POST / USER LOGIN ###
POST {{url}}/user/login
Content-Type: application/json

{
  "email": "Serra@gmail.com",
  "password": "supPergutesgeheimespassword-123"
}

### UPDATE USER DATA ###
PATCH {{url}}/user/62a6f394c8e66d8b453536b9
Content-Type: application/json

{
  "firstName": "Ivo"
}

### DELETE USER ###
DELETE {{url}}/user/62c424871bb5f1bbd8b9236b

### USER LOGOUT ###
POST {{url}}/user/logout
Content-Type: application/json



### FOLLLOW A USER ###

PATCH {{url}}/user/62c424871bb5f1bbd8b9236b/following
Content-Type: application/json
