@url = http://localhost:7000

### GET ALL USERS ###
GET {{url}}/user

### GET SEARCH RESULT ###
GET {{url}}/user/search/N

### GET USER BY ID ###
GET {{url}}/user/62a6f394c8e66d8b453536b9


### POST/REGISTER NEW USER ###
POST {{url}}/user/register
Content-Type: application/json

{
  "firstName": "jadel",
  "lastName": "smith",
  "profileName": "jade_smith",
  "profilePicture": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50",
  "email": "js@gravatar.com",
  "password": "supPergutesgeheimespassword-123",
  "confirmPassword": "supPergutesgeheimespassword-123",
  "userAddress": {
    "street": "123 Main St",
    "city": "city",
    "zip": "12345",
    "country": "france"
  }
}

### POST/REGISTER NEW USER ###
POST {{url}}/user/register
Content-Type: application/json

{
  "firstName": "Peter",
  "lastName": "Testman",
  "profileName": "TestiPet",
  "profilePicture": "",
  "email": "testman@gmail.com",
  "password": "supPergutesgeheimespassword-123",
  "confirmPassword": "supPergutesgeheimespassword-123",
  "userAddress": {
    "street": "test-allee.",
    "city": "Testhausen",
    "zip": "28133",
    "country": "germany"
  },
  "status":"Token test"
}


### POST / USER LOGIN ###
POST {{url}}/user/login
Content-Type: application/json

{
  "email": "testman@gmail.com",
  "password": "supPergutesgeheimespassword-321"
}

### UPDATE USER DATA ###
PATCH {{url}}/user/62c55076acc55d4c35d84627
Content-Type: application/json

{
  "password":"supPergutesgeheimespassword-321",
  "status": "new password test"
}

### DELETE USER ###
DELETE {{url}}/user/62c424871bb5f1bbd8b9236b

### USER LOGOUT ###
POST {{url}}/user/logout
Content-Type: application/json



### FOLLLOW A USER ###

PATCH {{url}}/user/62c424871bb5f1bbd8b9236b/following
Content-Type: application/json
